apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearops-api
  namespace: clearops
  labels:
    app: clearops-api
    tier: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: clearops-api
  template:
    metadata:
      labels:
        app: clearops-api
        tier: backend
    spec:
      containers:
        - name: api
          image: 948102249482.dkr.ecr.us-east-1.amazonaws.com/clearops-api:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
