name: terraform-ci
on:
  pull_request:
    paths: ['**/*.tf']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: |
          cd 12-terraform/stackforge
          terraform init -backend=false
          terraform validate

      - uses: terraform-linters/setup-tflint@v4
      - name: tflint
        run: |
          cd 12-terraform/stackforge
          tflint --init
          tflint

      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: true

      - uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
          soft_fail: true
